[package]
name = "pong"
version = "0.1.0"
authors = []
edition = "2018"


[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]


[dependencies.amethyst]
version = "0.13.0"
features = ["nightly"]